media: media
content:
  - name: blog
    label: 技术博客
    type: collection
    path: blog
    fields:
      - name: title
        label: 标题
        type: string
      - name: date
        label: 日期
        type: date
      - name: authors
        label: 作者
        type: string
        list: true
      - name: body
        label: 正文
        type: rich-text
  - name: workflow-docs
    label: 工作流文档
    type: collection
    path: docs
    fields:
      - name: title
        label: 标题
        type: string
      - name: body
        label: 正文
        type: rich-text
